/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientLogin.java
 *
 * Created on Nov 20, 2013, 4:43:03 PM
 */

package torrent.client;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.io.Serializable;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import torrent.client.ClientHome.Handler;

/**
 *
 * @author shiku
 */
public class ClientLogin extends javax.swing.JFrame {

    ObjectInputStream in;
    ObjectOutputStream out;
    /** Creates new form ClientLogin */
    public ClientLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        et_username = new javax.swing.JTextField();
        et_password = new javax.swing.JPasswordField();
        b_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Side");
        setBounds(new java.awt.Rectangle(400, 150, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Login"));

        jLabel1.setText("User Name :");

        jLabel2.setText("Password :");

        b_login.setText("Login");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_login)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(et_username)
                        .addComponent(et_password, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(et_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(et_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(b_login)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:

        try{
         Socket socket = new Socket("localhost", 9004);
        out = new ObjectOutputStream(socket.getOutputStream());

        // Process all messages from server, according to the protocol.
       // while (true) {

           
      //  } while ends
        if((et_username.getText()!=null) && (et_password.getText()!=null) )
        {
            user_info user= new user_info(et_username.getText(),et_password.getText());
            out.writeObject(et_username.getText());
            out.writeObject(et_password.getText());
            //out.flush();
            System.out.println("name : "+user._username+" pw: "+user._password);
            in = new ObjectInputStream(socket.getInputStream());
        
            String from_server = in.readObject().toString();
            if(from_server.equals("Successfull..."))
            {
            //jLabel3.setText("Login Succesful...");
            JOptionPane.showMessageDialog(null, "Login Successfull....", "Success", WIDTH, null);
                    Frame[] x = ClientLogin.getFrames();
                    x[0].setVisible(false);
                     String path = JOptionPane.showInputDialog("Enter Folder path...");

                   ClientHome y = new ClientHome(socket,in,out,user._username,path);

                    y.setVisible(true);
                    new Handler().start();


            }
            else
            {
              //  jLabel3.setText("Invalid User name or password... please try again..");
            et_username.setText("");
            et_password.setText("");
            et_username.grabFocus();
            }
            out.flush();
            //out.close();
        }
        else
        {
            //jLabel3.setText("Username password can't be null... please try again..");
            et_username.setText("");
            et_password.setText("");
            et_username.grabFocus();
        }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_b_loginActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ClientLogin().setVisible(true);
            }
        });

    }





    


   /*
     *A serializable class for storing username and password
     *
     */

    public static class user_info implements Serializable{
        private String _username;
        private String _password;

        public user_info(String username,String password)
        {
            this._username = username;
            this._password = password;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JPasswordField et_password;
    private javax.swing.JTextField et_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
